version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  main:
    jobs:
      - build_and_test